apiv1/urls.py
from django.conf.urls import url

from .views import ProfileAPIView

urlpatterns = [
    url(r'^user/(?P<pk>\d+)/$', ProfileAPIView.as_view(), name='update_profile'),
]

squats/urls.py
from django.conf.urls import include, url
from .views import CreateUserProfileView, EditUserProfileView, DisplayUserProfileView, IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^profile/new/$', CreateUserProfileView.as_view(), name="new-user-profile"),
    url(r'^users/(?P<pk>\d+)/$', DisplayUserProfileView.as_view(), name="display_user_profile"),
    url(r'^users/(?P<pk>\d+)/edit/$', EditUserProfileView.as_view(), name="edit-user-profile"),
]

squatsprofile/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from squats import urls as profile_urls
from apiv1 import urls as apiv1_urls
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(profile_urls, namespace='profile')),
    url(r'^apiv1/', include(apiv1_urls, namespace='apiv1')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

squats/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from taggit_autosuggest.managers import TaggableManager
from django.core.validators import MaxValueValidator
# Create your models here.

class Profile(models.Model):
	name = models.CharField(max_length=100)
	age = models.IntegerField(validators=[MaxValueValidator(150),])
	skills = TaggableManager(blank=True)
	image1 = models.FileField(upload_to='media/')
	image2 = models.FileField(upload_to='media/')
	PROFILE_IMAGE_CHOICES = (
		('dp1', "image1"),
		('dp2', "image2"),
	)
	profile_image = models.CharField(max_length=10,choices=PROFILE_IMAGE_CHOICES)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block css %} {% endblock %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Squats Profile</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'jquery-autosuggest/css/autoSuggest-grappelli.css' %}" media="all" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'jquery/dist/jquery.js' %}"></script>
    <link href="{% static 'x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'profile:index' %}">Squats Profiles</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href={% url 'profile:new-user-profile' %}>Create Profile</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content %} {% endblock %}
    </div>
    <!-- /.container -->


    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery-autosuggest/js/jquery.autoSuggest.minified.js' %}"> </script>
    <script src="{% static 'x-editable/dist/bootstrap3-editable/js/bootstrap-editable.js' %}"></script>
    {% block scripts %} {% endblock %}
</body>

</html>

templates/edit_user_profile.html
{% extends "base.html" %}
{% block css %}
{% endblock %}
{% block content %}
<h2 style="text-align:center">Your Squats Profile</h2>

<div class="card">
  <p><a class="edit-a" href="{% url 'profile:display_user_profile' object.pk %}"> Preview Profile</a></p>
  <img src="{{ dp_path }}" style="width:300px">
  <h3><span>Name</span>
  <a class="edit-a" href="#" id="name" data-type="text" data-placement="right" data-title="Enter username" data-url="{% url 'apiv1:update_profile' object.pk %}" data-pk="{{ object.pk }}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ object.name }}</a></h3>
  <h3><span>Age</span>
        <a class="edit-a" href="#" id="age" data-type="text" data-placement="right" data-title="Enter Age" data-url="{% url 'apiv1:update_profile' object.pk %}" data-pk="{{ object.pk }}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{{ object.age }}</a></h3>
  <span>Skills</span>
   	<a class="edit-a" href="#" id="skills" data-type="text" data-placement="right" data-title="Enter skills" data-url="{% url 'apiv1:update_profile' object.pk %}" data-pk="{{ object.pk }}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}">{% for skill in object.skills.all %}{{ skill.name }},{% endfor %}</a>
  <h3> Your Images </h3>
  <div>
  <a href="javascript:uploadAvatar('image1');"><img id="image1" width="300" class="img img-rounded" src="{{ object.image1.url }}"></a>
 </div>
 <br/> <br/>
 <div>
 <div>
  <a href="javascript:uploadAvatar('image2');"><img id="image2" width="300" class="img img-rounded" src="{{ object.image2.url }}"></a>
 </div>
</div>
<div class="modal fade" id="avatar_form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Upload Image</h4>
        <span id="error-message"></span>
      </div>
      <div class="modal-body">
          <form id="upload-file" method="post" enctype="multipart/form-data">
              <input type="hidden" id="avatar_user_id" name="avatar_user_id" value="{{ user.pk }}"/>
            <span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
            <span>Add files...</span>
                <input name="file" type="file" id="input-file">
            </span>
            <button id="upload-file-btn" type="button" class="btn btn-primary">Upload</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block scripts %}
<script type="text/javascript">
$.fn.editable.defaults.mode = 'inline';

    $('#name').editable({});
    $('#age').editable({});
    $('#skills').editable({});
    $('#profile_image').editable({});
</script>
<script type="text/javascript">
	function readURL(input, id) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $(id).attr('src', e.target.result);
            }
            
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    $("#id_image1").change(function(){
        readURL(this, "#image1");
    });
    $("#id_image2").change(function(){
        readURL(this, "#image2");
    });
</script>
<script type="text/javascript">
  function uploadAvatar(id)
          {
              $("#input-file").attr('name', id);
              $('#avatar_form').modal();
          }
</script>

<script>
  $(function () {
      $('#upload-file-btn').click(function () {
          var form_data = new FormData($('#upload-file')[0]);
          form_data.append('csrfmiddlewaretoken','{{csrf_token}}');
          $.ajax({
              type: 'POST',
              url: '/apiv1/user/'+$("#avatar_user_id").val()+'/',
              data: form_data,
              contentType: false,
              cache: false,
              processData: false,
              async: false,
              success: function (data) {              
                  $('#avatar_form').modal('hide');
                  if (data['image1']){
                    $("#image1").attr("src", data['image1']);
                  } else if (data['image2']) {
                    $("#image2").attr("src", data['image2']);    
                  }
              },
              error : function (data) {
                console.log(data);
                $('#error-message')[0].innerHTML = data.responseJSON.error;
              }
          });
      });
  });
</script>
{% endblock %}

templates/form-field-horizontal.html
{% load profile_utils %}
<div class="row form-field-horizontal">
    <div class="form-group{% if field.errors %} has-error{% endif %}">
        {% if field.html_name == 'skills' %}
        <label class="col-sm-2 control-label" for="id_{{ field.html_name }}">Skills</label>
        {% else %}
        <label class="col-sm-2 control-label" for="id_{{ field.html_name }}">{{ field.label }}</label>
        {% endif %}
        <div class="col-sm-4">
            {{ field|addclass:'form-control' }}
        </div>
        
        {% if field.html_name == 'image1' %}
            <span>
                <label for="id_profile_image_0"><input type="radio" name="profile_image" value="dp1" required class="form-control" id="id_profile_image_0" checked="check" />
                 Make it profile picture</label>                     
            </span>
        {% endif %}
        {% if field.html_name == 'image2' %}
            <span>
                <label for="id_profile_image_1"><input type="radio" name="profile_image" value="dp2" required class="form-control" id="id_profile_image_1" />
                 Make it profile picture</label>
            </span>
        {% endif %}
        <span class="help-block col-sm-9 col-sm-offset-2">
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ error }}
                {% endfor %}
            {% else %}
                {{ field.help_text }}
            {% endif %}
        </span>

    </div>    
</div>

templates/index.html
{% extends 'base.html'  %}

{% block content %}
    <a href={% url 'profile:new-user-profile' %}>
    	<button class="btn btn-default primaryAction">Create New Profile</button>
    </a>
    <br>
    <h3><p>Users Profile List</p></h3>
    <div class="row">
    <ul>
    	{% for user in object_list %}
    		<li>
    			<h3><a href="{% url 'profile:display_user_profile' user.pk %}">{{ user.name }}</a></h3>
    		</li>
    	{% endfor %}
    </ul>
    </div>
{% endblock %}

templates/user_profile.html
{% extends "base.html" %}
{% block css %}
{% endblock %}
{% block content %}
<h2 style="text-align:center">Your Squats Profile</h2>

<div class="card">
  <p><a class="edit-a" href="{% url 'profile:edit-user-profile' object.pk %}"> Edit Profile</a></p>
  <img src="{{ dp_path }}" style="width:300px">
  <h1>{{ object.name }}</h1>
  <h3>Age {{ object.age }}</h3>
  <h3>{% for skill in object.skills.all %}{{ skill.name }} {% endfor %}</h3>
  <h3> Your Images </h3>
  <div style="margin: 24px 0;">
    <img src="{{ object.image1.url }}" style="width:300px"> <br/> <br/>
    <img src="{{ object.image2.url }}" style="width:300px">
 </div>
</div>
{% endblock %}

templates/user_profile_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<form method="post" enctype="multipart/form-data">
		  	{% csrf_token %}
			{{ form.non_field_errors }}
			{% include 'form-field-horizontal.html' with field=form.name %}
			{% include 'form-field-horizontal.html' with field=form.age %}
			<div class="row form-group">
				{% include 'form-field-horizontal.html' with field=form.skills %}
			</div>
			<div class="row">
			    <div class="row">
			    	<div class="image-input">
				    	{% include 'form-field-horizontal.html' with field=form.image1 %}
			    	</div>
		    	</div>
		    	<div class="row">
    		    	<div class="image-display col-sm-6">
    			    	<img id="image1" src="#" width="300" />
    		    	</div>
		    	</div>
			</div>
			<div class="row">
			    {% include 'form-field-horizontal.html' with field=form.image2 %}
			    <img id="image2" src="#" width="300" />
			</div>

			        

			<div class="form-group">
				<div class="col-sm-10 col-sm-offset-2">
					<button type="submit" class="btn btn-primary primaryAction">Save</button>
				</div>
			</div>
		</form>		
	</div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
	function readURL(input, id) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $(id).attr('src', e.target.result);
            }
            
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    $("#id_image1").change(function(){
        readURL(this, "#image1");
    });
    $("#id_image2").change(function(){
        readURL(this, "#image2");
    });
</script>
{% endblock %}